services:
  - type: worker
    name: nexivo-whatsapp-bot
    env: node
    region: oregon
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: npm run bot
    autoDeploy: true
