services:
  - type: web
    name: nexivo-whatsapp-bot
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npx puppeteer browsers install chrome --path /opt/render/project/src/.cache/puppeteer
    startCommand: npm run bot
    autoDeploy: true
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.cache/puppeteer
